# HTTP configuration
server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081

  # Define request logging
  requestLog:
    timeZone: UTC
    appenders:
      # Settings for logging to a file.
      - type: file

        # The time zone in which dates should be displayed.
        timeZone: UTC

        # The file to which statements will be logged.
        #
        # If enabled is true, this must be specified.
        currentLogFilename: logs/harahachibu_request.log

        # When the log file rolls over, the file will be archived to
        # app-2012-03-15.log.gz, example.log will be truncated,
        # and new statements written to it.
        #
        # If archive is true, this must be specified.
        archivedLogFilenamePattern: logs/harahachibu_request-%d.log.gz

        # The maximum number of log files to archive.
        archivedFileCount: 5


# Proxy configuration details
proxy:

  # Status code to return when disk is full (default: 500)
  errorStatus: 500

  # List of URLs which should trigger a disk space check.
  # These are regular expressions, so may use full regex syntax
  # They may also include an HTTP method, which is *not* a regex -
  # ie. PUT and POST should be separate lines. If no method is given,
  # all requests to that path will be checked.
  checkUrls:
    - /solr/update
    - /solr/.*/update
    - POST /solr/.*/postUpdate
    - PUT /solr/.*/putUpdate

  # The proxy destination server prefix
  destinationServer: http://localhost:8983


diskSpace:

  # Checker type represents the type of checker to instantiate.
  # One of
  #   - elasticsearch, for built-in ES checker
  #   - solr, for built-in local Solr checker
  #   - TODO : solrCluster, for built-in clustered Solr checker (requires external processes
  #     to pass free space data to application)
  #   - TODO : Another implementation of uk.co.flax.harahachibu.services.DiskSpaceChecker
  checkerType: elasticsearch

  # The minimum amount of space required on the disk to pass the space check.
  # May be a single number of bytes, a number of Kilobytes, Megabytes or Gigabytes,
  # or a percentage, respectively represented as:
  #   - 123456
  #   - 128K
  #   - 512M
  #   - 16G
  #   - 5%
  threshold: 5%

  configuration:
    # Base URL for the Elasticsearch host (when checkerType == elasticsearch)
    baseURL: http://localhost:9200

    # Data directory for the local Solr instance (when checkerType == solr)
    dataDirectory: /data/solr


# Logging
logging:

  level: WARN

  loggers:
    # Set info logging for Flax code
    "uk.co.flax": INFO

  appenders:
    # Set up console logging
    - type: console
      threshold: WARN
      target: stderr

    # Set up file logging
    - type: file

      # Do not write log statements below this threshold to the file.
      threshold: ALL

      # The time zone in which dates should be displayed.
      timeZone: UTC

      # A custom Logback format string.
      logFormat: null

      # The file to which statements will be logged.
      #
      # If enabled is true, this must be specified.
      currentLogFilename: logs/harahachibu.log

      # When the log file rolls over, the file will be archived to
      # app-2012-03-15.log.gz, example.log will be truncated,
      # and new statements written to it.
      #
      # If archive is true, this must be specified.
      archivedLogFilenamePattern: logs/harahachibu-%d.log.gz

      # The maximum number of log files to archive.
      archivedFileCount: 5
